- import_playbook: pve/update_pve.yml
- import_playbook: update/update_arr.yml
- import_playbook: update/update_gpu.yml
- import_playbook: update/update_infomaniak.yml
- import_playbook: update/update_jumphost_cts.yml
- import_playbook: update/update_minix.yml
- import_playbook: update/update_networkcheckers_cts.yml
- import_playbook: update/update_nextcloud.yml
- import_playbook: update/update_other_cts.yml
- import_playbook: update/update_rsync_backup_cts.yml
- import_playbook: update/update_traefik_cts.yml
- import_playbook: update/update_uptimekuma_cts.yml
# - import_playbook: update_k3s.yml
