- hosts:
    - gpu
  gather_facts: false
  become: true
  roles:
    - update_cts
    - install_docker_debian
    - role: install_nginx
      courgettes_subdomain: "gpu"
    - install_gpu
    - install_ollama
    - install_tabby

- hosts:
    - pvenodes[0]
  gather_facts: false
  tasks:
    - name: Reboot gpu VM every night. Allows for GPU to reset consumption back to 10W instead of 17.
      ansible.builtin.cron:
        name: "reboot gpu"
        minute: "0"
        hour: "0"
        job: "/usr/sbin/qm reboot 302"
      become: yes
