ollama_models:
  - name: qwen2.5-coder
    version: 7b
    create_tool_variant: true
    context_size: 6144
  - name: llama3.1
    version: 8b
  - name: llama3.1
    version: 8b-instruct-q5_K_M
  - name: phi3.5
    version: 3.8b
  - name: nomic-embed-text
    version: 137m-v1.5-fp16
